name: publish

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: windows-latest
    env:
      Token: ${{ secrets.GH_PAT }}
      name: ${{ env.GITHUB_ACTOR }}
      email: ${{ secrets.EMAIL }}
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: dev
          ref: dev

      - name: Create variables for module cacher
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v3.5
        with:
          modules-to-cache: PSWordCloud, powershell-yaml

      - name: Run module cacher action
        id: cacher
        uses: actions/cache@v2
        with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}

      - name: Install PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        uses: potatoqualitee/psmodulecache@v3.5
      - name: Generate wordcloud and README.md
        shell: pwsh
        run: |
          ./gen-readme.ps1

      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
          ref: main

      - name: Publish
        shell: pwsh
        run: |
          Copy-Item $HOME\output\* $Home\main
          cd $Home\main
          git config user.name "$env:name"
          git config user.email "$env:email"
          git commit -a -m "GH Actions Commit"
          git push
